### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by tonyelation** [msolomonTMG/jira-comment-slack-notification#3]
This looks very interesting as we are looking for a way to send a slack message to our users when they are mentioned in Jira (ticket or confluence page).  Looks like this does that, but I don't see any documentation that outlines how to actually deploy or use this.  Can you explain how one would get this deployed to a Jira environment?  we are using the Jira Cloud.

**Comment by msolomonTMG** [comment]
@tonyelation  thank you for your interest in the project! I just merged #8 to help explain how this can be setup -- checkout the README and let me know if you have any questions!

Relates to #4
