### ISSUE TITLE
Add documentation to README about how to set this up

### ISSUE THREAD

**Issue by edahlseng** [msolomonTMG/jira-comment-slack-notification#4]
It would be awesome if the README had documentation on how to set this up with any Jira/Slack combo. @msolomonTMG I'm happy to submit a PR with this, just wanted to make sure you're good with me adding it before I put in the work!

**Comment by msolomonTMG** [comment]
Hey @edahlseng --  I appreciate your interest in the project!

I welcome PRs -- I just merged in #8 as a starting point. Feel free to expand on it
