### ISSUE TITLE
Package as a Docker image

### ISSUE THREAD

**Issue by edahlseng** [msolomonTMG/jira-comment-slack-notification#7]
To make it easier for people to consume this app, I think it would be awesome to have it package as a docker image. Then all that's need to run this app is to run the docker image with the associated environment variables. The docker image could be automatically run on a CI trigger for this repo.

Similar to the other issues that I created yesterday, I'm happy to put in the work to make this happen. What are your thoughts @msolomonTMG?

**Comment by msolomonTMG** [comment]
Hey @edahlseng I created a "Deploy to Heroku" button that I'm hoping could accomplish something similar and welcome installs from folks who arent so familiar with things like Docker. What are your thoughts on that?

**Comment by msolomonTMG** [comment]
Gotta be honest, I'm not sure. But I think adding the option for folks to deploy this as a docker container is a good thing since it shouldn't disrupt Heroku users.

I think that #6 would break the loading env variables for Heroku users that develop locally with the Heroku CLI unless I'm missing something

**Comment by edahlseng** [comment]
Awesome! As a first step, I'll put together a PR with a Dockerfile for packaging up this application. The next step after that is to integrate it into a CI workflow so that updated Docker images can automatically be pushed to Docker Hub. Do you want to host the Docker image on your personal account or create an organization for it?

#6 shouldn't break any of the env variable loading. All it does is shift the logic for pulling values out of environment variables into one file (checking out the `settings.js` file in that PR). Right now it might not seem like that adds a ton of benefit, but I have some thoughts on improving the parsing of those variables (for example, the need to exclude the trailing slash on the Jira URL ate up way more time than I'd like to admit when I was setting up the bot for the first time. Therefore, I'd like to put some parsing rules around the loading of that variable to control for those minute differences), and as we look to add more steps to how those variables are interpreted, it will help to have that logic all in one place.

**Comment by msolomonTMG** [comment]
Closing per #12
